# Generated by Django 3.2.6 on 2021-09-09 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3)),
                ('default_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('default_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('default_email_address', models.EmailField(blank=True, max_length=70, null=True)),
                ('default_adress_line1', models.CharField(blank=True, max_length=70, null=True)),
                ('default_adress_line2', models.CharField(blank=True, max_length=70, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=50, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=10, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
