# Generated by Django 3.2.6 on 2021-09-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_adress_line1',
            new_name='default_address_line1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_adress_line2',
            new_name='default_address_line2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_email_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_title',
        ),
    ]
