# Generated by Django 3.2.6 on 2021-09-04 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_item_sku'),
        ('shop_checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_size', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='shop_checkout.orderdetails')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemOrder',
        ),
    ]
