# Generated by Django 3.2.6 on 2021-09-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_checkout', '0003_auto_20210908_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='date',
            new_name='date_created',
        ),
    ]
