# Generated by Django 3.2.6 on 2021-09-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_checkout', '0005_auto_20210909_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='adress_line1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='adress_line2',
            new_name='address_line2',
        ),
    ]
