# Generated by Django 3.2.6 on 2021-09-10 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210910_0238'),
        ('shop_checkout', '0006_auto_20210909_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='profiles.userprofile'),
        ),
    ]
