# Generated by Django 3.2.6 on 2021-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_checkout', '0009_alter_orderdetails_billing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_key',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
