# Generated by Django 3.2.6 on 2021-08-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210816_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
